spring.application.name=risk-ai-platform

server.port=${PORT:1999}
server.address=0.0.0.0

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://zephyr.proxy.rlwy.net:25587/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ollama.api.url=${OLLAMA_API_URL:http://localhost:11434/api/generate}
ollama.model=${OLLAMA_MODEL:llama3.1}